# Renders the "Sponsor" button on the repo.
# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [tiagomoraes]   # https://github.com/sponsors/tiagomoraes
ko_fi: tiagomoraes      # https://ko-fi.com/tiagomoraes
